# Generated by Django 4.0.6 on 2023-05-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patientdata_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='entryBox',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='feedback',
            field=models.TextField(blank=True, default='No feedback'),
        ),
    ]
